### PR TITLE
Added cache to dateparser

### PR DESCRIPTION
**Pull request by Midas847**
Description:
PR to add the code developed as part of C4GT" 23

Changes:
Added the code developed as part of C4GT" 23

Test:
image

To DO
- [x] Add caching to dateparser
- [x] Made caching as optional
- [x] Added performance benchmark using jest

### CODE REVIEW

**Comment by techsavvyash** [comment]
Hey, try using [this](https://docs.nestjs.com/techniques/caching)

**Comment by ChakshuGautam** [comment]
Hey @Midas847 two small things on this front
- Can you publish a performance benchmark for this? You can update the last test to do this.
- Can you make caching optional as part of the constructor?

**Comment by Midas847** [comment]
Hey @ChakshuGautam I made caching as optional and added the performance benchmark for this.

**Comment by ChakshuGautam** [comment]
Is it improving speed. Can wr see some benchmarks?

**Comment by Midas847** [comment]
Hey @ChakshuGautam , so this is the one without caching:
image
This is the one with caching:
image

**Comment by ChakshuGautam** [comment]
It's slower than the older code that was generating 1M/second.

**Comment by techsavvyash** [comment]
Closing this out since this approach didn't result in the expected outcome.
Thanks a lot for the PR @Midas847.

**Pull request closed without merging**
